### ISSUE TITLE
Broken after 12.3.1 Update

### ISSUE THREAD

**Issue by mikedvzo** [xilopaint/alfred-urban-dictionary#7]
ERROR in Workflow

[17:12:03.583] Urban Dictionary[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7A5D8E36-C63D-4909-BA23-FE8C3F8D3386%3EE9F6C624-C607-49DB-9856-3E16605772E2)] Queuing argument 'LOL'
[17:12:05.016] Urban Dictionary[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7A5D8E36-C63D-4909-BA23-FE8C3F8D3386%3EE9F6C624-C607-49DB-9856-3E16605772E2)] Script with argv '(null)' finished
[17:12:05.017] ERROR: Urban Dictionary[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7A5D8E36-C63D-4909-BA23-FE8C3F8D3386%3EE9F6C624-C607-49DB-9856-3E16605772E2)] Code 1: .
17:12:03 workflow.py:2299 DEBUG    ---------- Urban Dictionary (2.1.1) ----------
17:12:04 workflow.py:2321 ERROR    Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/divincem/Library/Mobile Documents/com~apple~CloudDocs/Sync/Alfred 4/Alfred.alfredpreferences/workflows/user.workflow.7A5D8E36-C63D-4909-BA23-FE8C3F8D3386/workflow/workflow.py", line 2314, in run
    func(self)
  File "urban_dictionary.py", line 24, in main
    data = json.loads(res.read())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
17:12:05 workflow.py:2345 DEBUG    ---------- finished in 1.297s ----------
[17:12:05.021] Urban Dictionary[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.7A5D8E36-C63D-4909-BA23-FE8C3F8D3386%3EE9F6C624-C607-49DB-9856-3E16605772E2)] {
  "items": [
    {
      "title": "Error in workflow 'Urban Dictionary'",
      "subtitle": "Expecting value: line 1 column 1 (char 0)",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}

**Comment by mikedvzo** [comment]
Looks like DNS Content Filtering Issue

**Comment by xilopaint** [comment]
The workflow should be ported to Python 3 as the macOS 12.3 update removed Python 2. I'll release a fix in the coming days.

**Comment by xilopaint** [comment]
@mikedvzo I can't reproduce your issue. Do you still have the issue with the [latest version](https://github.com/xilopaint/alfred-urban-dictionary/releases/latest)?

**Comment by mikedvzo** [comment]
No, I do not! As stated above, the problem is not with the Workflow but with Cisco Open DNS blocking Urban Dictionary as adult content. Cisco Open DNS has gotten ridiculous with its rules.
